## İşletim sistemlerinde "Environment Variable" .env
## Ortam Değişkenlerir
## Ortam değişkeleri ilgili bilgisayarın configurasyonunu tutar, her PC için
## farklı uygulamalar ve ayarlar olduğu için burası pc ye özel bir Key-Value
## bilgileri tutar. Bu nedenle farklı developerlar bilgilerini genellikle
## ortam değişkenlerinde alarak okuyabilirler.
## İşletimsisteminin env bilgisini okumak için ${KEY_NAME} şeklinde yazmanız yeterlidir.
## DİKKAT!!! env değeri uygulama başlatıldıktan sonra eklenirse uygulama bu değeri çekemez.

server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5444/SpringSatisDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop # create, create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Burada yazılanlar tamamen kenidimizin oluşturduğu configler
my-application:
  naber-genclik: "iyidir hocam"
  depo: "Ankara-DEV"
  depo2: ${DEPO_ADI}
  kullanici-bilgileri:
    user-name: "muhammet hoca"
    password: "123456"

